server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
#    url: jdbc:mysql://124.71.154.121:3306/backend_demo
    url: jdbc:mysql://106.15.106.190:3306/backend
    username: admin
    password: 12345

    driver-class-name: com.mysql.cj.jdbc.Driver

#    redis的配置
  redis:
    host: 101.132.138.14
    port: 6379
    timeout: 20000
    password: DRT1951725
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      indent_output: false

  output:
    ansi:
      enabled: detect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

      ## mail config ##
      #163 SMTP

  mail:
    host: smtp.163.com
    #postmail information
    #MCIWYKFGGFGQECIK
    username: drt_test@163.com
    password: MCIWYKFGGFGQECIK
    default-encoding: utf-8
    port: 465
    properties: { mail.smtp.ssl.enable: "true" }

    ## thymeleaf config##
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

    ## default config ##
mail:
  from:
    addr: drt_test@163.com

file:

#  upload-dir: /Users/dengruotao/Desktop/SEproject_2021/back-end/src/main/resources/static
#  upload-dir: /Users/frederickmo/documents/Github/SEproject_2021/back-end/src/main/resources/static
#  upload-dir:/Users/86133/Documents/GitHub/SEproject_2021/back-end/src/main/resources/static
  upload-dir: /home/admin/backend

# Sa-Token Configuration
sa-token:
  # token name (also figured as cookie name)
  token-name: satoken
  # token term of validity: unit :seconds / 30days default / -1 means no expiration
  timeout: 604800
  # token temporary term of validity (validity expires when no operations during a certain period of time) unit: second
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: true
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: false
  # token??
  token-style: uuid
  # ????????
  is-log: true

  jwt-secret-key: frederickmo



